platform :ios, '7.0'
pod 'SVGKit', :git => "https://github.com/SVGKit/SVGKit.git"
pod 'Facebook-iOS-SDK', '~> 3.13.0'
pod 'SDWebImage', '~> 3.6.0'
pod 'CRToast', '~> 0.0.6'
pod 'MBProgressHUD', '~> 0.8'
